@extends('layouts.main', ['type' => $type])

@section('title', $title)

@section('content')
<div class="container terms">
  <h2><strong> Terms & Conditions </strong></h2>
  <p>Welcome to Amazonas. Amazonas Services LLC provide website features and other products and services to you when you visit or shop, use Amazonas products or services, or use software provided by Amazonas in connection with any of the foregoing. Amazonas provides the Amazonas Services subject to the following conditions.</p>
  <h4><strong>By using Amazonas Services, you agree to these conditions. Please read them carefully.</strong></h4>
  <p>We offer a wide range of Amazonas Services, and sometimes additional terms may apply. When you use an Amazonas Service (for example, Your Profile) you also will be subject to the guidelines, terms and agreements applicable to that Amazonas Service ("Service Terms"). If these Conditions of Use are inconsistent with the Service Terms, those Service Terms will control.</p>
  <h4><strong>COPYRIGHT</strong></h4>
  <p>All content included in or made available through any Amazonas Service, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software is the property of Amazonas or its content suppliers and protected by United States and international copyright laws. The compilation of all content included in or made available through any Amazonas Service is the exclusive property of Amazonas and protected by U.S. and international copyright laws.</p>
  <h4><strong>TRADEMARKS</strong></h4>
  <p>Graphics, logos, page headers, button icons, scripts, and service names included in or made available through any Amazonas Service are trademarks or trade dress of Amazonas in the U.S. and other countries. Amazonas trademarks and trade dress may not be used in connection with any product or service that is not Amazonas, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Amazonas. All other trademarks not owned by Amazonas that appear in any Amazonas Service are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Amazonas.</p>
  <h4><strong>PATENTS</strong></h4>
  <p>One or more patents owned by Amazonas apply to the Amazonas Services and to the features and services accessible via the Amazonas Services. Portions of the Amazonas Services operate under license of one or more patents.</p>
  <h4><strong></strong></h4>
  <p>Subject to your compliance with these Conditions of Use and any Service Terms, and your payment of any applicable fees, Amazonas or its content providers grant you a limited, non-exclusive, non-transferable, non-sublicensable license to access and make personal and non-commercial use of the Amazonas Services. This license does not include any resale or commercial use of any Amazonas Service, or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of any Amazonas Service or its contents; any downloading, copying, or other use of account information for the benefit of any third party; or any use of data mining, robots, or similar data gathering and extraction tools. All rights not expressly granted to you in these Conditions of Use or any Service Terms are reserved and retained by Amazonas or its licensors, suppliers, publishers, rightsholders, or other content providers. No Amazonas Service, nor any part of any Amazonas Service, may be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of Amazonas. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Amazonas without express written consent. You may not use any meta tags or any other "hidden text" utilizing Amazonas name or trademarks without the express written consent of Amazonas. You may not misuse the Amazonas Services. You may use the Amazonas Services only as permitted by law. The licenses granted by Amazonas terminate if you do not comply with these Conditions of Use or any Service Terms.</p>
  <h4><strong>YOUR ACCOUNT</strong></h4>
  <p>You may need your own Amazonas account to use certain Amazonas Services, and you may be required to be logged in to the account and have a valid payment method associated with it. If there is a problem charging your selected payment method, we may charge any other valid payment method associated with your account. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your account, and you agree to accept responsibility for all activities that occur under your account or password. Amazonas does sell products for children, but it sells them to adults, who can purchase with a permitted payment method. If you are under 18, you may use the Amazonas Services only with involvement of a parent or guardian. Amazonas reserves the right to refuse service, terminate accounts, terminate your rights to use Amazonas Services, remove or edit content, or cancel orders in its sole discretion.</p>
  <h4><strong>REVIEWS AND OTHER CONTENT</strong></h4>
  <p>You may post reviews, and other content and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights (including publicity rights), or otherwise injurious to third parties or objectionable, and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam" or unsolicited commercial electronic messages. You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Amazonas reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.</p>
  <p>If you do post content or submit material, and unless we indicate otherwise, you grant Amazonas a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, perform, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant Amazonas and sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify Amazonas for all claims resulting from content you supply. Amazonas has the right but not the obligation to monitor and edit or remove any activity or content. Amazonas takes no responsibility and assumes no liability for any content posted by you or any third party.</p>
  <h4><strong>RISK OF LOSS</strong></h4>
  <p>All purchases of physical items from Amazonas are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</p>
  <h4><strong>PRODUCT DESCRIPTIONS</strong></h4>
  <p>Amazonass attempts to be as accurate as possible. However, Amazonas does not warrant that product descriptions or other content of any Amazonas Service is accurate, complete, reliable, current, or error-free. If a product offered by Amazonas itself is not as described, your sole remedy is to return it in unused condition.</p>
  <h4><strong>PRICING</strong></h4>
  <p>"Price" means the suggested retail price of a product as provided by a manufacturer, supplier, or seller. We regularly check List Prices against prices recently found on Amazonas and other retailers.</p>
  <h4><strong>SANCTIONS AND EXPORT POLICY</strong></h4>
  <p>You may not use any Amazonas Service if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using Amazonas Services. You must comply with all U.S. or other export and re-export restrictions that may apply to goods, software (including Amazonas Software), technology, and services.</p>
  <h4><strong>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</strong></h4>
  <p>THE AMAZONAS SERVICES AND ALL INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) AND OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE AMAZONAS SERVICES ARE PROVIDED BY AMAZONAS ON AN "AS IS" AND "AS AVAILABLE" BASIS, UNLESS OTHERWISE SPECIFIED IN WRITING. AMAZONAS MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE AMAZONAS SERVICES, OR THE INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE AMAZONAS SERVICES, UNLESS OTHERWISE SPECIFIED IN WRITING. YOU EXPRESSLY AGREE THAT YOUR USE OF THE AMAZONAS SERVICES IS AT YOUR SOLE RISK.</p>
  <p>TO THE FULL EXTENT PERMISSIBLE BY LAW, AMAZONAS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. AMAZONAS DOES NOT WARRANT THAT THE AMAZONAS SERVICES, INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE AMAZONAS SERVICES, AMAZONAS SERVERS OR ELECTRONIC COMMUNICATIONS SENT FROM AMAZONAS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. TO THE FULL EXTENT PERMISSIBLE BY LAW, AMAZONAS WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF ANY AMAZONAS SERVICE, OR FROM ANY INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH ANY AMAZONAS SERVICE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE SPECIFIED IN WRITING.</p>
  <h4><strong>APPLICABLE LAW</strong></h4>
  <p>By using any Amazonas Service, you agree that the Federal Arbitration Act, applicable federal law, and the laws of the state of Washington, without regard to principles of conflict of laws, will govern these Conditions of Use and any dispute of any sort that might arise between you and Amazon.</p>
  <h4><strong>SITE POLICIES, MODIFICATION, AND SEVERABILITY</strong></h4>
  <p>We reserve the right to make changes to our site, policies, Service Terms, and these Conditions of Use at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.</p>
  <h4><strong>OUR ADDRESS</strong></h4>
  <p>Faculdade de Engenharia da Universidade do Porto</p>
  <p>Rua Dr. Roberto Frias, s/n 4200-465 Porto PORTUGAL</p>
</div>
@endsection
